### ISSUE TITLE
Class notions missing - super and extends

### ISSUE THREAD

**Issue by srebalaji** [mbeaudru/modern-js-cheatsheet#49]
class Example {
 static Callme() {
 console.log("Static method");
 }
}
Example.Callme();

Output:
Static method

**Comment by mbeaudru** [comment]
As well as *static* keyword, it would be nice to have explanations on the *super* keyword usage as well as *extends*.

This topic being quite hard to summarize and since I'm quite short in time these days, I have decided to put on many external resources as a temporary solution.

But yeah, *class* notion is lacking explanation and details at the moment and this needs to be done. If you want to begin the work with a PR you are welcomed 👍 .

**Comment by iifeoluwa** [comment]
Hi @srebalaji, are you picking this up? If not, I could send in a PR for it.
Thanks!

**Comment by mbeaudru** [comment]
Fixed by [PR #63](https://github.com/mbeaudru/modern-js-cheatsheet/pull/63).

*super* and *extends* notions are still missing tho, so if you want to do a PR for this it's welcomed! Otherwise I will do it when I have some time 👍
