### ISSUE TITLE
Project name is misleading

### ISSUE THREAD

**Issue by timotgl** [mbeaudru/modern-js-cheatsheet#51]
While I'm sure it's a good resource, people coming here looking for an actual sheet or sheet-like document (which limits the amount of information it can contain) would be disappointed. Sorry to be so pedantic, but maybe consider renaming it to guide, compendium, or something?

Edit: just read that you're calling it "guide" in the README already..

**Comment by mbeaudru** [comment]
Hi @timotgl , many people have been complaining about the name both on Reddit and Hackernews so you're not alone.

I understand where the complaints are coming from, but I named it a *cheatsheet* because everything is held in a single page document. This is why I made the repo in the first place ; every notion treated here has an explanation on the web but it was hard to find them all summarized in a single document.

It was hard to find a name for this though, because people might have been complaning about the doc not being a guide but a list of notions. *Compendium* seems to be it, but I'm not sure everyone knows the word (I didn't 😅).

Besides, I didn't thought that the repo would have had such an audience in the first place so I might have choosen a better name if I had seen this coming. Now it is how it is and I don't think changing the name would be a good idea for it's visibility since people have forked it and the repo has been spread.
